name: Hello world workflow
on:
  push:
    branches:
     -master
  pull_request:
    branches:
      -master
  workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: sunflower
         run: echo "Sunflower"
         shell: bash
  goodbye:    
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash

     

     
